comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        branches:
          - Dev
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
        Branched:
          - Dev
