---
title: "References"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{References}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


* [MSToolkit - An R library for simulating and evaluating clinical trial designs and scenarios, Smith MK, Pugh R](https://www.page-meeting.org/default.asp?id=33&keuze=abstract-view&goto=profile&profile_id=588&abstract_id=1518) Presented at PAGE meeting 2009, St. Petersburg, Russia & ACOP 2009, Foxwoods, CT, USA.

* [MSToolkit](https://www.londonr.org/?s=mstoolkit) Presentation at LondonR, 2nd March 2010

Other manuscripts describing approaches to simulation:

* [Determination of model appropriateness. Williams PJ, Ette E. In “Simulation for Designing Clinical Trials” pp74-103, Kimko and Duffull eds, Marcel Dekker, NY](https://www.routledge.com/Simulation-for-Designing-Clinical-Trials-A-Pharmacokinetic-Pharmacodynamic/Kimko-Duffull/p/book/9780824708627)

* [Importance of protocols for simulation studies in clinical drug development. Smith MK, Marshall A. Stat Methods Med Res. 2011 Dec;20(6):613-22. doi: 10.1177/0962280210378949](https://pubmed.ncbi.nlm.nih.gov/20688782/)

* [Decision-Making in Drug Development: Application of a Model Based Framework for Assessing Trial Performance. Smith MK, French JL, Kowalski KG, Hutmacher MM, Ewy W. in “Clinical Trial Simulation - applications and trends” pp61-83, Kimko and Peck eds, Springer, NY](https://link.springer.com/book/10.1007/978-1-4419-7415-0)

* [A Quantitative Approach for Making Go/No-Go Decisions in Drug Development. Chuang-Stein C, Kirby S, French JL, Kowalski KG, Marshall SF, Smith MK, Bycott P, Beltangady M.Therapeutic Innovation & Regulatory Science Vol 45, Issue 2, pp. 187 - 202](https://journals.sagepub.com/doi/abs/10.1177/009286151104500213)

* [Modeling and simulation to support dose selection and clinical development of SC-75416, a selective COX-2 inhibitor for the treatment of acute and chronic pain. Kowalski KG, Olson S, Remmers AE, Hutmacher MM. Clin Pharmacol Ther. 2008 Jun;83(6):857-66.](https://pubmed.ncbi.nlm.nih.gov/17882158/)

* [Model-based drug development. Lalonde R, Kowalski K, Hutmacher M, Ewy W, Nichols D, Milligan P, et al. Clin Pharmacol Ther. 2007 Jul;82(1):21-32](https://pubmed.ncbi.nlm.nih.gov/17522597/)

* [Model-based drug development: a rational approach to efficiently accelerate drug development. Milligan PA, Brown MJ, Marchant B, Martin SW, van der Graaf PH, Benson N, Nucci G, Nichols DJ, Boyd RA, Mandema JW, Krishnaswami S, Zwillich S, Gruben D, Anziano RJ, Stock TC, Lalonde RL. Clin Pharmacol Ther. 2013 Jun;93(6):502-14. doi: 10.1038/clpt.2013.54.](https://pubmed.ncbi.nlm.nih.gov/23588322/)