test_that("test.createNmMatrix", {
  expect_true(all.equal(createNmMatrix(1:3), cbind(1:2, 2:3)))
  expect_true(all.equal(createNmMatrix(1:6), cbind(c(1:2, 4), c(2:3, 5), 4:6)))
  bigMat <- createNmMatrix(1:10, list(LETTERS[1:4], letters[1:4]))
  expect_true(all(bigMat[,1] == c(1, 2, 4, 7)))
  expect_true(all(bigMat[,2] == c(2, 3, 5, 8)))
  expect_true(all(bigMat[,3] == c(4:6, 9)))
  expect_true(all(bigMat[,4] == 7:10))
  expect_true(all(dimnames(bigMat)[[1]] == LETTERS[1:4]))
  expect_true(all(dimnames(bigMat)[[2]] == letters[1:4]))
  expect_true(all.equal(createNmMatrix( cbind(1:2, 1)), cbind(1:2, 2:1)))
  expect_true(all.equal(createNmMatrix(1), cbind(1)))
  expect_true(!length(createNmMatrix(NULL)))
  expect_error(createNmMatrix(cbind(1:3, 1:3)))
  expect_error(createNmMatrix(1:2))
})
